<!doctype html>
<html lang="fr" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title><?= APP_NAME; ?><?= $title ?? null; ?></title>

    <?php if (isset($styles) && is_array($styles)) : ?>
        <?php foreach ($styles as $link) : ?>
            <link href="<?= $link ?>" rel="stylesheet">
        <?php endforeach; ?>
    <?php endif; ?>

</head>
<body>